(() => {
  'use strict';
  const APP_NAME = 'BalanceBite';
  const NOTE = 'Note: This output is generated by open weight model';
  const DISCLAIMER = 'General guidance, not medical advice. Check with your doctor or dietitian.';

  const DEFAULT_AVATAR = 'data:image/svg+xml;utf8,' + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><defs><clipPath id="c"><circle cx="100" cy="100" r="100"/></clipPath>' +
    '<linearGradient id="s" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#c3e6ff"/><stop offset="1" stop-color="#f1faff"/></linearGradient></defs>' +
    '<g clip-path="url(#c)"><rect width="200" height="200" fill="url(#s)"/><ellipse cx="85" cy="42" rx="30" ry="14" fill="#fff"/><circle cx="82" cy="32" r="14" fill="#fff"/>' +
    '<path d="M0 140 Q60 112 120 128 T200 124 V200 H0Z" fill="#c8e386"/><path d="M30 200 Q70 128 140 132 Q175 134 200 150 V200Z" fill="#8aa400"/></g></svg>');

  const $ = (s) => document.querySelector(s);
  const state = { profile: null, mode: 'meal', step: 'stock', stock: '', busy: false, last: null, photo: null };

  function el(tag, props = {}, ...kids) {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(props)) {
      if (k === 'class') n.className = v;
      else if (k === 'text') n.textContent = v;
      else n.setAttribute(k, v);
    }
    for (const k of kids.flat()) if (k != null) n.append(k.nodeType ? k : document.createTextNode(String(k)));
    return n;
  }
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const show = (id) => ['setup', 'chat'].forEach((s) => ($('#' + s).hidden = s !== id));

  let toastTimer;
  function toast(msg) {
    const t = $('#toast');
    t.textContent = msg; t.classList.add('show');
    clearTimeout(toastTimer); toastTimer = setTimeout(() => t.classList.remove('show'), 1800);
  }

  /* ---------------- profile screen ---------------- */
  function openSetup(canGoBack) {
    const p = state.profile || {};
    $('#f-name').value = p.name || '';
    $('#f-health').value = p.health || '';
    $('#f-restrict').value = p.restrictions || '';
    $('#f-allergy').value = p.allergies || '';
    state.photo = p.photo || null;
    $('#avatar-preview').src = state.photo || DEFAULT_AVATAR;
    $('#form-error').textContent = '';
    $('#back').hidden = !canGoBack;
    show('setup');
  }

  $('#photo').addEventListener('change', (e) => {
    const file = e.target.files[0];
    if (!file || !file.type.startsWith('image/')) return;
    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        const size = 256, c = document.createElement('canvas');
        c.width = c.height = size;
        const s = Math.min(img.width, img.height);
        c.getContext('2d').drawImage(img, (img.width - s) / 2, (img.height - s) / 2, s, s, 0, 0, size, size);
        state.photo = c.toDataURL('image/jpeg', 0.85);
        $('#avatar-preview').src = state.photo;
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  });

  $('#profile-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const p = {
      name: $('#f-name').value.trim(),
      health: $('#f-health').value.trim(),
      restrictions: $('#f-restrict').value.trim(),
      allergies: $('#f-allergy').value.trim(),
      photo: state.photo,
    };
    if (!p.name || !p.health) { $('#form-error').textContent = 'Please enter your name and health issue.'; return; }
    const res = await window.api.saveProfile(p);
    if (!res.ok) { $('#form-error').textContent = res.message || 'Could not save.'; return; }
    state.profile = res.profile;
    openChat();
  });
  $('#back').addEventListener('click', openChat);

  /* ---------------- chat ---------------- */
  function openChat() {
    const src = state.profile.photo || DEFAULT_AVATAR;
    $('#avatar-small').src = src;
    show('chat');
    resetChat();
  }

  function resetChat() {
    $('#log').replaceChildren();
    state.step = 'stock'; state.stock = ''; state.last = null;
    document.querySelectorAll('#modes .chip').forEach((c) => c.classList.toggle('on', c.dataset.mode === state.mode));
    clearQuick();
    if (state.mode === 'meal') {
      addMsg('bot', `Hi ${state.profile.name}! What do you have in stock? Mention the vegetables, spices, egg/meat, milk products.`);
    } else {
      addMsg('bot', 'Which ingredients are in the dish you want to try? Add quantities if you know them.');
    }
    $('#msg').focus();
  }

  function addMsg(who, text) {
    const b = el('div', { class: 'bubble ' + who, text });
    $('#log').append(b); scroll();
    return b;
  }
  const scroll = () => { const l = $('#log'); l.scrollTop = l.scrollHeight; };
  const clearQuick = () => $('#quick').replaceChildren();

  function showSkip() {
    clearQuick();
    const b = el('button', { class: 'chip', type: 'button', text: 'Skip' });
    b.addEventListener('click', () => handle('skip'));
    $('#quick').append(b);
  }

  $('#modes').addEventListener('click', (e) => {
    const b = e.target.closest('.chip'); if (!b || state.busy) return;
    state.mode = b.dataset.mode; resetChat();
  });
  $('#new-chat').addEventListener('click', () => { if (!state.busy) resetChat(); });
  $('#open-profile').addEventListener('click', () => { if (!state.busy) openSetup(true); });

  $('#composer').addEventListener('submit', (e) => {
    e.preventDefault();
    const text = $('#msg').value.trim();
    if (!text || state.busy) return;
    $('#msg').value = '';
    handle(text);
  });

  async function handle(text) {
    if (state.busy) return;
    clearQuick();
    addMsg('user', text);
    if (state.mode === 'check') return run({ ingredients: text });
    if (state.step === 'stock') {
      state.stock = text; state.step = 'nutrients';
      addMsg('bot', 'Which nutrients do you want more of today? (for example protein, fibre)');
      showSkip();
      return;
    }
    const nutrients = /^(skip|none|no|nothing)$/i.test(text) ? '' : text;
    return run({ stock: state.stock, nutrients });
  }

  function setBusy(b) { state.busy = b; $('#send').disabled = b; $('#msg').disabled = b; }

  async function run(input) {
    setBusy(true);
    const wait = el('div', { class: 'bubble bot wait' },
      el('span', { id: 'status', text: 'Thinking' }), el('span', { class: 'dots' }, el('span', { text: '.' }), el('span', { text: '.' }), el('span', { text: '.' })));
    $('#log').append(wait); scroll();
    try {
      const res = await window.api.generate(state.mode, input);
      wait.remove();
      if (!res.ok) { addMsg('bot', res.message || 'Something went wrong.'); }
      else {
        showResult(state.mode, res.data);
        if (state.mode === 'meal') {
          state.step = 'stock';
          addMsg('bot', 'Want another plan? Tell me what is in stock.');
        } else addMsg('bot', 'Want to check another dish? List its ingredients.');
      }
    } catch (err) {
      wait.remove(); addMsg('bot', 'Something went wrong. Please try again.');
    } finally { setBusy(false); $('#msg').focus(); }
  }

  /* ---------------- result: one neutral model -> card, clipboard text, .doc ---------------- */
  function buildModel(mode, d) {
    const m = [];
    if (mode === 'meal') {
      m.push({ t: 'title', text: 'Meal plan' });
      m.push({ t: 'center', text: "Today's menu: " + d.recipes.map((r) => r.name).join(', ') });
      d.recipes.forEach((r) => {
        m.push({ t: 'h', text: r.name });
        m.push({ t: 'field', label: 'Ingredients', text: r.ingredients.join(', ') });
        m.push({ t: 'list', label: 'Steps', items: r.steps, ordered: true });
        m.push({ t: 'list', label: 'Nutrients', items: r.nutrients.map((n) => `${n.item} helps with ${n.nutrient}`) });
        m.push({ t: 'field', label: 'How it helps you', text: r.why_it_helps });
        m.push({ t: 'field', label: 'Warning', text: r.warning });
      });
    } else {
      const lvl = Math.max(0, ['OK to eat', 'Eat in limited portion', 'Better to avoid'].indexOf(d.verdict));
      m.push({ t: 'title', text: 'Food check' });
      m.push({ t: 'field', label: 'Dish', text: d.ingredients });
      m.push({ t: 'verdict', text: d.verdict, level: lvl });
      m.push({ t: 'field', label: 'Why', text: d.reason });
      m.push({ t: 'field', label: 'Portion at one sitting', text: d.portion });
      m.push({ t: 'field', label: 'Probable after-effects', text: d.after_effects });
      m.push({ t: 'field', label: 'Tip', text: d.tip });
    }
    return m;
  }

  function toDom(model) {
    const root = el('div', { class: 'output' }, el('p', { class: 'note', text: NOTE }));
    for (const i of model) {
      if (i.t === 'title') root.append(el('h2', { text: i.text }));
      else if (i.t === 'center') root.append(el('p', { class: 'menu', text: i.text }));
      else if (i.t === 'h') root.append(el('h3', { text: i.text }));
      else if (i.t === 'verdict') root.append(el('p', { class: 'verdict v-' + i.level, text: i.text }));
      else if (i.t === 'field') root.append(el('p', {}, el('strong', { text: i.label + ': ' }), i.text));
      else if (i.t === 'list') root.append(el('p', {}, el('strong', { text: i.label + ':' })),
        el(i.ordered ? 'ol' : 'ul', {}, i.items.map((x) => el('li', { text: x }))));
    }
    root.append(el('p', { class: 'fine', text: DISCLAIMER }));
    return root;
  }

  function toText(model) {
    const out = [NOTE, ''];
    for (const i of model) {
      if (i.t === 'title') out.push(i.text.toUpperCase());
      else if (i.t === 'center' || i.t === 'verdict') out.push(i.text);
      else if (i.t === 'h') out.push('', i.text);
      else if (i.t === 'field') out.push(`${i.label}: ${i.text}`);
      else if (i.t === 'list') out.push(`${i.label}:`, ...i.items.map((x, k) => (i.ordered ? `  ${k + 1}. ${x}` : `  - ${x}`)));
    }
    out.push('', DISCLAIMER);
    return out.join('\n');
  }

  function toDocHtml(model) {
    const colors = ['#3f7d00', '#b26a00', '#e5342a'];
    let b = `<p style="color:#e5342a;text-align:center;font-size:10pt">${esc(NOTE)}</p>`;
    for (const i of model) {
      if (i.t === 'title') b += `<h1 style="text-align:center;font-family:Calibri,Arial">${esc(i.text)}</h1>`;
      else if (i.t === 'center') b += `<p style="text-align:center;font-size:13pt">${esc(i.text)}</p>`;
      else if (i.t === 'h') b += `<h2 style="font-family:Calibri,Arial;margin-top:22pt">${esc(i.text)}</h2>`;
      else if (i.t === 'verdict') b += `<p style="text-align:center;font-size:16pt;font-weight:bold;color:${colors[i.level]}">${esc(i.text)}</p>`;
      else if (i.t === 'field') b += `<p><b>${esc(i.label)}:</b> ${esc(i.text)}</p>`;
      else if (i.t === 'list') {
        const tag = i.ordered ? 'ol' : 'ul';
        b += `<p><b>${esc(i.label)}:</b></p><${tag}>${i.items.map((x) => `<li>${esc(x)}</li>`).join('')}</${tag}>`;
      }
    }
    b += `<p style="color:#555;font-size:9pt;margin-top:24pt">${esc(DISCLAIMER)}</p>`;
    return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"` +
      `><head><meta charset="utf-8"><title>${esc(model[0].text)}</title></head>` +
      `<body style="font-family:Calibri,Arial;font-size:12pt">${b}</body></html>`;
  }

  const ICON_COPY = '<svg viewBox="0 0 24 24" width="26" height="26" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><rect x="8" y="8" width="12" height="13" rx="3"/><path d="M16 8V5a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h2"/></svg>';
  const ICON_DL = '<svg viewBox="0 0 24 24" width="26" height="26" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12m-5-5 5 5 5-5M4 21h16"/></svg>';

  function showResult(mode, data) {
    const model = buildModel(mode, data);
    const copy = el('button', { class: 'icon-btn', type: 'button', 'aria-label': 'Copy to clipboard', title: 'Copy to clipboard' });
    const save = el('button', { class: 'icon-btn', type: 'button', 'aria-label': 'Save as .doc', title: 'Save as .doc' });
    copy.innerHTML = ICON_COPY; save.innerHTML = ICON_DL; // static icons only, no model text
    copy.addEventListener('click', async () => { await window.api.copy(toText(model)); toast('Copied to clipboard'); });
    save.addEventListener('click', async () => {
      const r = await window.api.saveDoc(toDocHtml(model), model[0].text);
      if (r.ok) toast('Saved');
    });
    $('#log').append(el('div', { class: 'result' }, toDom(model), el('div', { class: 'actions' }, copy, save)));
    scroll();
  }

  /* ---------------- start ---------------- */
  (async function init() {
    document.title = APP_NAME;
    $('#app-title').textContent = APP_NAME;
    window.api.onStatus((s) => { const n = $('#status'); if (n) n.textContent = s.replace(/\.+$/, ''); });
    state.profile = await window.api.getProfile();
    state.profile ? openChat() : openSetup(false);
  })();
})();
